schema_version = "1.0.0"

id = "pribambase"
version = "2.6.5"
name = "Pribambase"
tagline = "Paint pixel-art textures in Blender using Aseprite"
maintainer = "Iken-O"
type = "add-on"
website = "https://github.com/Iken-O/Pribambase-Part2"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2021 lampysprites",
  "2023-2026 Iken-O",
]

tags = ["Paint", "UV", "Animation", "Material"]
platforms = ["windows-x64", "linux-x64"]

wheels = [
  "./wheels/aiohappyeyeballs-2.6.1-py3-none-any.whl",
  "./wheels/aiohttp-3.13.5-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/aiohttp-3.13.5-cp311-cp311-win_amd64.whl",
  "./wheels/aiohttp-3.13.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/aiohttp-3.13.5-cp313-cp313-win_amd64.whl",
  "./wheels/aiosignal-1.4.0-py3-none-any.whl",
  "./wheels/async_timeout-5.0.1-py3-none-any.whl",
  "./wheels/attrs-26.1.0-py3-none-any.whl",
  "./wheels/frozenlist-1.8.0-cp311-cp311-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl",
  "./wheels/frozenlist-1.8.0-cp311-cp311-win_amd64.whl",
  "./wheels/frozenlist-1.8.0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl",
  "./wheels/frozenlist-1.8.0-cp313-cp313-win_amd64.whl",
  "./wheels/idna-3.15-py3-none-any.whl",
  "./wheels/multidict-6.7.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/multidict-6.7.1-cp311-cp311-win_amd64.whl",
  "./wheels/multidict-6.7.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/multidict-6.7.1-cp313-cp313-win_amd64.whl",
  "./wheels/propcache-0.5.2-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/propcache-0.5.2-cp311-cp311-win_amd64.whl",
  "./wheels/propcache-0.5.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/propcache-0.5.2-cp313-cp313-win_amd64.whl",
  "./wheels/typing_extensions-4.15.0-py3-none-any.whl",
  "./wheels/yarl-1.23.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/yarl-1.23.0-cp311-cp311-win_amd64.whl",
  "./wheels/yarl-1.23.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/yarl-1.23.0-cp313-cp313-win_amd64.whl",
]

[permissions]
files = "Open sprite files and manage temp images"
network = "Sync with the Aseprite companion app"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
]
